const LOCALIZATION_KEYS = {
  BASE_CURRENCY_REQUIRED: 'BASE_CURRENCY_REQUIRED',
  QUOTE_CURRENCY_REQUIRED: 'QUOTE_CURRENCY_REQUIRED',
  BASE_AMOUNT_REQUIRED: 'BASE_AMOUNT_REQUIRED',
  NOT_SUPPORTED_BASE_CURRENCY: 'NOT_SUPPORTED_BASE_CURRENCY',
  NOT_SUPPORTED_QUOTE_CURRENCY: 'NOT_SUPPORTED_QUOTE_CURRENCY',
  BASE_AMOUNT_NOT_NUMBER: 'BASE_AMOUNT_NOT_NUMBER',
  BASE_AMOUNT_NOT_INTEGER: 'BASE_AMOUNT_NOT_INTEGER',
  UNKNOWN_REQUEST: 'UNKNOWN_REQUEST',
  SERVER_ERROR: 'SERVER_ERROR',
};

module.exports = LOCALIZATION_KEYS;
